services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:Z
    depends_on:
      - db

  db:
    image: docker.io/library/mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsb_frais
      MYSQL_USER: gsb_user
      MYSQL_PASSWORD: gsb_pass
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:Z
      - gsb_db_data:/var/lib/mysql

volumes:
  gsb_db_data:
